### ISSUE TITLE
How to parse the University of Houston 13 dataset?

### ISSUE THREAD

**Issue by detectRecog** [lms-07/CVSSN#1]
Hello, great work! 
It is difficult for beginners to obtain the UH dataset (.mat files required by this repo) and the train/test splits. Could you please help to provide instructions to extract these mat files from the originally provided .tif files? Or, could you please provide links for researchers like me?

**Comment by lms-07** [comment]
Hi, thanks for your interest!

In Python, directly read .tif data or images and then convert them into the .mat format. In fact, I employ the **imread** fun in the ### tifffile package to read .tif, and the common **savemat** fun to save as .mat data. In addition, based on my coding experiences, the ### gdal package is able to implement format conversion, but it may be more complicated.

Good lack！
