### ISSUE TITLE
Need SSSAN tensorflow code

### ISSUE THREAD

**Issue by HITchina** [lms-07/CVSSN#2]
Hello Dear,
I have read your paper and used your code can you provide the SSSAN model tensorflow code? but given the Pytorch implementation. i am working on tensorflow I will be very thankful to you.

**Comment by lms-07** [comment]
Hello bro，

Thanks for your interest in our work. It is certain that I could provide the source code of SSSAN, which is based on Keras and TensorFlow and part of the total framework, i.e., just method implementation. Now, I am at home, and when I am in school next week, I can send you the discussed code. If yes, you could email me your WeChat number or by email.

**Comment by HITchina** [comment]
Hello Dear,
             I am very thankful for your kind response. here is my wechat ID(TAS_Tahir) and the email as same you sent me email. kindly add me on wechat. I am also working on Hyperspectral Image Classification at Harbin Institute of Technology China. I am also IEEE Transaction reviewer we can discuss some ideas or we can collaborate.

BR,Tahir Arshad   
    On Tuesday, October 3, 2023 at 09:14:39 AM GMT+5, Mingsong Li ***@***.***> wrote:  
 
 


Hello bro，

Thanks for your interest in our work. It is certain that I could provide the source code of SSSAN, which is based on Keras and TensorFlow and part of the total framework, i.e., just method implementation. Now, I am at home, and when I am in school next week, I can send you the discussed code. If yes, you could email me your WeChat number or by email.

**Comment by lms-07** [comment]
Hello Bro，

It is my pleasure for further communication.

**Comment by leezhien** [comment]
hello dear，How do I run 0 and 6 in model_list that I don't see defined during training

**Comment by lms-07** [comment]
> hello dear，How do I run 0 and 6 in model_list that I don't see defined during training

Hi，
Sorry, I cannot catch your clear meaning. You could explain your problems or needs.

**Comment by leezhien** [comment]
> > hello dear，How do I run 0 and 6 in model_list that I don't see defined during training
> 
> Hi， Sorry, I cannot catch your clear meaning. You could explain your problems or needs.

 Hi, in process_dl.py, the two models ContextualNet and A2S2 in model_list, they belong to model_3d_spa_set, but I don't see the model_type_flag that defines them, so it reports an error during the training process, how to solve this problem, I appreciate it!

**Comment by HITchina** [comment]
Hello dear,
                 I have attached a file where you can find the instructions on how you run the different models.
    On Saturday, September 21, 2024 at 03:57:43 PM GMT+5, Mingsong Li ***@***.***> wrote:  
 
 



hello dear，How do I run 0 and 6 in model_list that I don't see defined during training


Hi，
Sorry, I cannot catch your clear meaning. You could explain your problems or needs.

**Comment by leezhien** [comment]
> Hello dear,                  I have attached a file where you can find the instructions on how you run the different models. On Saturday, September 21, 2024 at 03:57:43 PM GMT+5, Mingsong Li ***@***.***> wrote: hello dear，How do I run 0 and 6 in model_list that I don't see defined during training Hi， Sorry, I cannot catch your clear meaning. You could explain your problems or needs. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
Hi, I apologize, I can't seem to find the attachment, could you send a copy to my email, I would greatly appreciate it!2102692112@qq.com

**Comment by lms-07** [comment]
> > > hello dear，How do I run 0 and 6 in model_list that I don't see defined during training
> > 
> > 
> > Hi， Sorry, I cannot catch your clear meaning. You could explain your problems or needs.
> 
> Hi, in process_dl.py, the two models ContextualNet and A2S2 in model_list, they belong to model_3d_spa_set, but I don't see the model_type_flag that defines them, so it reports an error during the training process, how to solve this problem, I appreciate it!

Hi, bro. I see, and it is fine since you figure out a small bug for our files. 
You could add '0' and '6' into model_spa_set, and I neglected this issue when organizing the code：）
I will update the corresponding files.
Thanks and good luck.
